apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: kip
spec:
  selector:
    matchLabels:
      app: kip
      tier: web
  template:
    metadata:
      labels:
        app: kip
        tier: web
    spec:
      containers:
      - name: kip-app
        image: kipelovets/homepage:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sharp-focus-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
  labels:
    app: kip
spec:
  defaultBackend:
    service:
      name: homepage-backend
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-backend
  labels:
    app: kip
spec:
  type: NodePort
  selector:
    app: kip
    tier: web
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - sharpfocus.app
---