name: Deploy
on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Build
        run: make build
      - name: Publish image to Docker Hub
        run: make publish

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          service_account: 'github-kip@${{ secrets.GKE_PROJECT }}.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - run: |-
          gcloud container clusters get-credentials "sharp-focus" --zone "europe-west1"
      - name: Deploy
        run: |-
          make deploy